import { agency, agent, service } from "@/shared/constants/images"
import { AgentReviewCardProps } from "./agent-review-card"
import { AgentServiceCardProps } from "./agent-service-card"
import { Property } from "@/features/properties/types/properties.type"
import { Agency } from "@/features/search/components/agency-card"
import { Agent } from "../types/agent.type"
import { Service } from "@/features/services/types/services.type"

export const AGENT_REVIEWS: AgentReviewCardProps[] = [
    {
        name: "John Doe",
        review: "Absolutely outstanding service! The agent went above and beyond to find me the perfect property in Downtown Dubai. Their knowledge of the market, attention to detail, and negotiation skills saved me both time and money. Highly professional and always responsive. I couldn't have asked for a better experience!",
        rating: 5,
        date: "2021-01-01",
        amenities: ["Parking", "Gym", "Swimming Pool"],
    },
    {
        name: "Jane Doe",
        review: "Great experience overall. The agent was knowledgeable and helped me find a beautiful apartment in Dubai Marina. The process was smooth and they were always available to answer my questions. Only minor issue was some delays in paperwork, but everything worked out in the end. Would definitely recommend!",
        rating: 4,
        date: "2021-01-02",
        amenities: ["Parking", "Gym", "Swimming Pool"],
    },
    {
        name: "Jim Doe",
        review: "Decent service, but there's room for improvement. The agent showed me several properties and was generally helpful, but I felt the communication could have been better. Some viewings were not well organized and I had to follow up multiple times. Eventually found a property that works for me.",
        rating: 3,
        date: "2021-01-03",
        amenities: ["Parking", "Gym", "Swimming Pool"],
    },
    {
        name: "Jill Doe",
        review: "Disappointed with the service. The agent seemed more interested in closing deals quickly rather than understanding my needs. Several properties shown were not what I asked for, and there was a lack of transparency about additional fees. Expected better professionalism.",
        rating: 2,
        date: "2021-01-04",
        amenities: ["Parking", "Gym", "Swimming Pool"],
    },
    {
        name: "Jack Doe",
        review: "Very poor experience. The agent was unprofessional, frequently late for viewings, and provided inaccurate information about properties. When issues arose, they were unresponsive and unhelpful. Had to find another agent to complete my property search. Would not recommend.",
        rating: 1,
        date: "2021-01-05",
        amenities: ["Parking", "Gym", "Swimming Pool"],
    },
    {
        name: "Sarah Ahmed",
        review: "Not satisfied with the level of service. While the agent was polite, they lacked knowledge about the areas I was interested in and couldn't answer basic questions about the properties. The follow-up was inconsistent and I felt my concerns weren't taken seriously.",
        rating: 2,
        date: "2021-01-06",
        amenities: ["Parking", "Gym", "Swimming Pool"],
    },
    {
        name: "Michael Chen",
        review: "Extremely unprofessional and unreliable. Appointments were cancelled last minute without proper explanation, and the agent showed properties that were completely out of my budget despite clear instructions. Wasted several weeks before switching to another agent. Not recommended at all.",
        rating: 1,
        date: "2021-01-07",
        amenities: ["Parking", "Gym", "Swimming Pool"],
    },
]

export const AGENT_SERVICES: AgentServiceCardProps[] = [
    {
        title: "Property Inspection",
        description: "Comprehensive property inspection service covering structural integrity, electrical systems, plumbing, and overall condition assessment.",
        price: 1000,
        image: agent.agentImage1,
    },
    {
        title: "Property Valuation",
        description: "Professional property valuation based on current market trends, comparable sales, and location analysis for accurate pricing.",
        price: 1500,
        image: agent.agentImage1,
    },
    {
        title: "Home Staging Consultation",
        description: "Expert advice on preparing your property for sale including furniture arrangement, decor suggestions, and presentation tips.",
        price: 800,
        image: agent.agentImage1,
    },
    {
        title: "Mortgage Advisory",
        description: "Get connected with the best mortgage providers and receive guidance on financing options tailored to your budget.",
        price: 500,
        image: agent.agentImage1,
    },
    {
        title: "Legal Documentation Assistance",
        description: "Complete support with all legal paperwork including contracts, NOCs, title deeds, and transfer documentation.",
        price: 1200,
        image: agent.agentImage1,
    },
    {
        title: "Property Marketing Package",
        description: "Full marketing service including professional photography, video tours, social media promotion, and listing on premium platforms.",
        price: 2000,
        image: agent.agentImage1,
    },
    {
        title: "Virtual Property Tour",
        description: "High-quality 3D virtual tours and video walkthroughs allowing buyers to explore properties remotely.",
        price: 750,
        image: agent.agentImage1,
    },
    {
        title: "Relocation Services",
        description: "Complete relocation support including area tours, school information, utility setup, and community orientation.",
        price: 1800,
        image: agent.agentImage1,
    },
    {
        title: "Investment Consultation",
        description: "Strategic investment advice on property portfolios, ROI analysis, rental yield projections, and market opportunities.",
        price: 2500,
        image: agent.agentImage1,
    },
    {
        title: "Property Management Setup",
        description: "Assistance with setting up property management including tenant screening, lease agreements, and maintenance coordination.",
        price: 1500,
        image: agent.agentImage1,
    },
]

export const PROPERTY_CARDS: Property[] = [
    {
        id: "1",
        title: "Luxury Villa in Palm Jumeirah",
        price: 100000,
        location: "Palm Jumeirah, Dubai",
        bedrooms: 3,
        bathrooms: 2,
        area: 1000,
        amenities: ["Private Beach Access", "Infinity Pool", "Smart Home System", "Private Garden", "Sea View", "Security 24/7"],
        status: "Ready",
    },
    {
        id: "2",
        title: "Modern Apartment in Downtown Dubai",
        price: 200000,
        location: "Downtown Dubai, Dubai",
        bedrooms: 4,
        bathrooms: 3,
        area: 1500,
        amenities: ["Gym", "Swimming Pool", "Concierge Service", "Covered Parking", "Children's Play Area", "BBQ Area"],
        status: "Ready",
    },
    {
        id: "3",
        title: "Spacious Townhouse in Arabian Ranches",
        price: 300000,
        location: "Arabian Ranches, Dubai",
        bedrooms: 5,
        bathrooms: 4,
        area: 2000,
        amenities: ["Golf Course View", "Community Pool", "Parks & Lakes", "Kids Play Area", "Tennis Courts", "Retail Center"],
        status: "Ready",
    },
    {
        id: "4",
        title: "Penthouse in Dubai Marina",
        price: 400000,
        location: "Dubai Marina, Dubai",
        bedrooms: 6,
        bathrooms: 5,
        area: 2500,
        amenities: ["Rooftop Terrace", "Jacuzzi", "Panoramic Views", "Valet Parking", "Private Elevator", "Walk-in Closets"],
        status: "Ready",
    },
    {
        id: "5",
        title: "Beachfront Villa in Jumeirah Beach Residence",
        price: 500000,
        location: "Jumeirah Beach Residence, Dubai",
        bedrooms: 7,
        bathrooms: 6,
        area: 3000,
        amenities: ["Beach Front", "Private Pool", "Maid's Room", "Landscaped Garden", "Outdoor Kitchen", "Cinema Room"],
        status: "Off-Plan",
    },
    {
        id: "6",
        title: "Contemporary Apartment in Business Bay",
        price: 600000,
        location: "Business Bay, Dubai",
        bedrooms: 8,
        bathrooms: 7,
        area: 3500,
        amenities: ["Canal View", "Fitted Kitchen", "Built-in Wardrobes", "Balcony", "Steam & Sauna", "Residents Lounge"],
        status: "Off-Plan",
    },
    {
        id: "7",
        title: "Elegant Villa in Emirates Hills",
        price: 700000,
        location: "Emirates Hills, Dubai",
        bedrooms: 9,
        bathrooms: 8,
        area: 4000,
        amenities: ["Golf Course", "Driver's Room", "Home Office", "Wine Cellar", "Gym Room", "Spa & Wellness Center"],
        status: "Off-Plan",

    },
]

export const AGENCIES: Agency[] = [
    {
        id: "1",
        name: "Prime Properties Dubai",
        profession: ["Real Estate Agency", "Property Management"],
        location: "Dubai UAE",
        rating: 4.7,
        reviews: 234,
        subscription: "Elite",
        specialization: ["Luxury Villas", "Commercial Spaces", "Investment Properties"],
        noOfAgents: 45,
        email: "prime.properties.dubai@example.com",
        image: agency.agencyLogo1,
    },
    {
        id: "2",
        name: "Global Realty Group",
        profession: ["International Real Estate", "Relocation Services"],
        location: "London UK",
        rating: 4.8,
        reviews: 412,
        subscription: "Elite",
        specialization: ["Prime Central London", "Corporate Housing", "Expat Services"],
        noOfAgents: 78,
        email: "global.realty.group@example.com",
        image: agency.agencyLogo2,
    },
    {
        id: "3",
        name: "Metro Real Estate Solutions",
        profession: ["Residential Sales", "Rental Services"],
        location: "New York USA",
        rating: 4.5,
        reviews: 189,
        subscription: "Pro",
        specialization: ["Manhattan Apartments", "Brooklyn Properties", "Co-op Sales"],
        noOfAgents: 32,
        email: "metro.real.estate@example.com",
        image: agency.agencyLogo3,
    },
    {
        id: "4",
        name: "Al Sahara Properties",
        profession: ["Real Estate Brokerage", "Investment Advisory"],
        location: "Riyadh Saudi Arabia",
        rating: 4.6,
        reviews: 156,
        subscription: "Pro",
        specialization: ["Commercial Real Estate", "Residential Compounds", "Land Development"],
        noOfAgents: 28,
        email: "al.sahara.properties@example.com",
        image: agency.agencyLogo4,
    },
    {
        id: "5",
        name: "Skyline Property Consultants",
        profession: ["Property Consultancy", "Valuation Services"],
        location: "Singapore",
        rating: 4.9,
        reviews: 327,
        subscription: "Elite",
        specialization: ["Condominiums", "Landed Properties", "Commercial Leasing"],
        noOfAgents: 52,
        email: "skyline.property.consultants@example.com",
        image: agency.agencyLogo5,
    },
    {
        id: "6",
        name: "Coastal Realty Partners",
        profession: ["Real Estate Agency"],
        location: "Miami USA",
        rating: 4.4,
        reviews: 98,
        subscription: "Standard",
        specialization: ["Waterfront Properties", "Luxury Condos", "Vacation Homes"],
        noOfAgents: 18,
        email: "coastal.realty.partners@example.com",
        image: agency.agencyLogo6,
    },
    {
        id: "7",
        name: "Heritage Properties Ltd",
        profession: ["Estate Agency", "Property Sales"],
        location: "Abu Dhabi UAE",
        rating: 4.3,
        reviews: 145,
        subscription: "Standard",
        specialization: ["Residential Properties", "Off-Plan Sales", "Property Management"],
        noOfAgents: 22,
        email: "heritage.properties.ltd@example.com",
        image: agency.agencyLogo1,
    },
    {
        id: "8",
        name: "Maple Leaf Realty",
        profession: ["Real Estate Brokerage", "Mortgage Services"],
        location: "Toronto Canada",
        rating: 4.5,
        reviews: 203,
        subscription: "Pro",
        specialization: ["Residential Sales", "New Developments", "Investment Properties"],
        noOfAgents: 35,
        email: "maple.leaf.realty@example.com",
        image: agency.agencyLogo2,
    },
    {
        id: "9",
        name: "Pearl Real Estate",
        profession: ["Property Agency"],
        location: "Doha Qatar",
        rating: 4.2,
        reviews: 87,
        subscription: "Basic",
        specialization: ["Apartments", "Villas", "Commercial Spaces"],
        noOfAgents: 12,
        email: "pearl.real.estate@example.com",
        image: agency.agencyLogo3,
    },
    {
        id: "10",
        name: "Prestige International Realty",
        profession: ["Luxury Real Estate", "Portfolio Management", "Concierge Services"],
        location: "Monaco",
        rating: 4.9,
        reviews: 178,
        subscription: "Elite",
        specialization: ["Ultra-Luxury Properties", "Penthouses", "International Investments"],
        noOfAgents: 24,
        email: "prestige.international.realty@example.com",
        image: agency.agencyLogo4,
    }
];

export const AGENTS: Agent[] = [
    {
        id: "1",
        name: "John Smith",
        email: "john.smith@example.com",
        profession: ["Estate Agent", "Real Estate Broker"],
        location: "Dubai UAE",
        rating: 4.5,
        reviews: 100,
        subscription: "Pro",
        specialization: ["Residential Properties", "Luxury Villas", "Downtown Apartments"],
        isTeamMember: true,
        image: agent.agentImage1,
    },
    {
        id: "2",
        name: "Sarah Johnson",
        email: "sarah.johnson@example.com",
        profession: ["Property Consultant", "Investment Advisor"],
        location: "Abu Dhabi UAE",
        rating: 4.8,
        reviews: 156,
        subscription: "Elite",
        specialization: ["Commercial Real Estate", "Investment Properties", "Portfolio Management"],
        image: agent.agentImage2,
    },
    {
        id: "3",
        name: "Mohammed Al-Rashid",
        email: "mohammed.al-rashid@example.com",
        profession: ["Commercial Real Estate Agent"],
        location: "Riyadh Saudi Arabia",
        rating: 4.6,
        reviews: 89,
        subscription: "Pro",
        specialization: ["Office Spaces", "Retail Properties", "Industrial Buildings"],
        isTeamMember: true,
        image: agent.agentImage3,
    },
    {
        id: "4",
        name: "Emily Chen",
        email: "emily.chen@example.com",
        profession: ["Residential Property Specialist"],
        location: "Singapore",
        rating: 4.9,
        reviews: 203,
        subscription: "Elite",
        specialization: ["Condominiums", "HDB Flats", "Landed Properties"],
        image: agent.agentImage4,
    },
    {
        id: "5",
        name: "David Martinez",
        email: "david.martinez@example.com",
        profession: ["Luxury Real Estate Advisor"],
        location: "London UK",
        rating: 4.7,
        reviews: 142,
        subscription: "Pro",
        specialization: ["Penthouses", "Prime Central London", "Historic Properties"],
        image: agent.agentImage5,
    },
    {
        id: "6",
        name: "Fatima Hassan",
        email: "fatima.hassan@example.com",
        profession: ["Real Estate Broker", "Legal Consultant"],
        location: "Doha Qatar",
        rating: 4.3,
        reviews: 67,
        subscription: "Basic",
        specialization: ["Residential Sales", "Property Law", "Contract Negotiation"],
        image: agent.agentImage6,
    },
    {
        id: "7",
        name: "James Wilson",
        email: "james.wilson@example.com",
        profession: ["Property Investment Manager"],
        location: "Toronto Canada",
        rating: 4.5,
        reviews: 98,
        subscription: "Standard",
        specialization: ["Multi-Family Properties", "REITs", "Property Development"],
        isTeamMember: true,
        image: agent.agentImage7,
    },
    {
        id: "8",
        name: "Aisha Abdullah",
        email: "aisha.abdullah@example.com",
        profession: ["Real Estate Agent", "Mortgage Advisor"],
        location: "Kuwait City Kuwait",
        rating: 4.8,
        reviews: 178,
        subscription: "Elite",
        specialization: ["First-Time Buyers", "Mortgage Solutions", "Waterfront Properties"],
        image: agent.agentImage8,
    },
    {
        id: "9",
        name: "Robert Thompson",
        email: "robert.thompson@example.com",
        profession: ["Commercial Property Specialist"],
        location: "New York USA",
        rating: 4.4,
        reviews: 124,
        subscription: "Pro",
        specialization: ["Manhattan Office Buildings", "Co-working Spaces", "Mixed-Use Developments"],
        image: agent.agentImage1,
    },
    {
        id: "10",
        name: "Layla Ahmed",
        email: "layla.ahmed@example.com",
        profession: ["Estate Agent", "Property Developer"],
        location: "Sharjah UAE",
        rating: 4.6,
        reviews: 91,
        subscription: "Basic",
        specialization: ["New Developments", "Off-Plan Properties", "Family Homes"],
        image: agent.agentImage2,
    }
];

export const SERVICES: Service[] = [
    {
        id: "1",
        name: "Professional Property Valuation",
        industries: ["Real Estate", "Valuation", "Consulting"],
        location: "Dubai UAE",
        rating: 4.8,
        reviews: 156,
        price: 2500,
        image: service.serviceImage1,
    },
    {
        id: "2",
        name: "Home Staging & Interior Design",
        industries: ["Interior Design", "Home Staging", "Real Estate"],
        location: "London UK",
        rating: 4.9,
        reviews: 203,
        price: 3500,
        image: service.serviceImage2,
    },
    {
        id: "3",
        name: "Mortgage Advisory Services",
        industries: ["Finance", "Mortgage", "Consulting"],
        location: "New York USA",
        rating: 4.6,
        reviews: 142,
        price: 1500,
        image: service.serviceImage3,
    },
    {
        id: "4",
        name: "Property Legal Documentation",
        industries: ["Legal", "Real Estate", "Documentation"],
        location: "Riyadh Saudi Arabia",
        rating: 4.7,
        reviews: 98,
        price: 2000,
        image: service.serviceImage4,
    },
    {
        id: "5",
        name: "Real Estate Photography & Videography",
        industries: ["Photography", "Videography", "Marketing"],
        location: "Singapore",
        rating: 4.9,
        reviews: 287,
        price: 800,
        image: service.serviceImage5,
    },
    {
        id: "6",
        name: "Property Management Solutions",
        industries: ["Property Management", "Maintenance", "Real Estate"],
        location: "Abu Dhabi UAE",
        rating: 4.5,
        reviews: 124,
        price: 5000,
        image: service.serviceImage1,
    },
    {
        id: "7",
        name: "Investment Portfolio Analysis",
        industries: ["Investment", "Finance", "Consulting"],
        location: "Toronto Canada",
        rating: 4.8,
        reviews: 167,
        price: 3000,
        image: service.serviceImage2,
    },
    {
        id: "8",
        name: "Architectural Consultation",
        industries: ["Architecture", "Design", "Construction"],
        location: "Doha Qatar",
        rating: 4.4,
        reviews: 89,
        price: 4500,
        image: service.serviceImage3,
    },
    {
        id: "9",
        name: "Property Inspection & Survey",
        industries: ["Inspection", "Surveying", "Real Estate"],
        location: "Miami USA",
        rating: 4.7,
        reviews: 178,
        price: 1200,
        image: service.serviceImage4,
    },
    {
        id: "10",
        name: "Real Estate Marketing & PR",
        industries: ["Marketing", "PR", "Digital Marketing"],
        location: "Monaco",
        rating: 4.9,
        reviews: 234,
        price: 6000,
        image: service.serviceImage5,
    }
];